# -----------------------------------------------------------------------------------------------------------------------------#
# Docker Compose Configuration
# -----------------------------------------------------------------------------------------------------------------------------#
version: '3'

services:
  docu-motion:
    build: .
    container_name: docu_motion_app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always
