# -----------------------------------------------------------------------------------------------------------------------------#
# Docker Compose Configuration
# -----------------------------------------------------------------------------------------------------------------------------#

services:
  docu-motion:
    build: .
    container_name: docu_motion_app
    ports:
      - "8505:8501"
    volumes:
      - .:/app
      - ./models_cache:/app/models
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    restart: always
